### PR TITLE
Disconnect on error creating new db

### LINKED ISSUE #2155: Immediately disconnect a database if connect fails from bad creds
This can lead cause confusion about the onboarding actually working

### PR DESCRIPTION
**Pull request by aguillenv**
Resolves #2155

### CODE REVIEW

**Review by dfellis — APPROVED** [review]

File: dashboard/src/components/providers/AppProvider.tsx [hunk 1]
```diff
@@ -424,6 +424,13 @@ const middlewareReducer = async (
         `,
         );
       } catch (e: any) {
+        middlewareReducer(config, dispatch, {
```
Comment (depombo) [inline dashboard/src/components/providers/AppProvider.tsx:427]: why is this not a dispatch call?

**Review by depombo — APPROVED** [review]

File: dashboard/src/components/providers/AppProvider.tsx (hunk 1 above)
Comment (aguillenv) [reply dashboard/src/components/providers/AppProvider.tsx:427]: In the `AppProvider` we have a `middleware` where we do the complex logic + API calls and then that's transferred to the `reducer` where we just make the transformations needed to the state and return. If we are inside the `middleware` a `dispatch` call will continue directly to the `reducer` but in this case we want to pass though the `middleware` again to make the API call to actually disconnect.
