### PR TITLE
Handle connection interruptions

### LINKED ISSUE #2164: Disconnect error
My main suspicion is a problem with next.js `run` endpoint. While a query is executing behind scenes, then the disconnect occurs and causes the failure for the dashboard due to an unhandled exception. This is because `disconnect` kills all open connections.

### PR DESCRIPTION
**Pull request by aguillenv**
Resolves #2164

### CODE REVIEW

File: dashboard/src/pages/api/run.ts [hunk 1]
```diff
@@ -108,8 +108,18 @@ async function runSql(sql: string, dbAlias: string, username: string, password:
       host: baseConnConfig.host,
       ssl: baseConnConfig.extra.ssl,
     });
+    // Based on https://node-postgres.com/apis/client#error
+    connTemp.on('error', e => {
```
Comment (dfellis) [inline dashboard/src/pages/api/run.ts:112]: Should we also pass the `res` object through to here and if this case is hit return an error to the front-end?

File: dashboard/src/pages/api/run.ts [hunk 2]
```diff
@@ -108,8 +108,18 @@ async function runSql(sql: string, dbAlias: string, username: string, password:
...
+        app: 'run',
+        env: process.env.IASQL_ENV,
+        meta: {
+          error: e.message,
+          stack: e.stack,
+        },
+      });
+    });
     await connTemp.connect();
-    // await connTemp.query(dbMan.setPostgresRoleQuery(database));
```
Comment (depombo) [inline dashboard/src/pages/api/run.ts:112]: why is the commented out? Isn't just catching the error enough

Comment (aguillenv) [reply dashboard/src/pages/api/run.ts:112]: this line was commented, I just removed assuming is not necessary

File: dashboard/src/pages/api/run.ts (hunk 1 above)
Comment (aguillenv) [reply dashboard/src/pages/api/run.ts:112]: I think we cannot since the listener is defined already in the `pg` lib. For the cases when this is hit due to `disconnect` killing open connections, it is ok not to do anything since that's exactly what disconnect is doing, cancel all ongoing paths.

Comment (dfellis) [reply dashboard/src/pages/api/run.ts:112]: hmm, so the handler is being defined within the `runSql` function call so each call will get a new handler. This means that we could make `res` another argument to `runSql` and then use it here as part of the closure.

Whether that's actually necessary is something else; in this particular case, no, but if there's an error in the future due to some other issue the error could be useful.

Comment (aguillenv) [reply dashboard/src/pages/api/run.ts:112]: ohh I see your point, yes that could be useful. I could give it a try in this PR

File: dashboard/src/pages/api/run.ts (hunk 2 above)
Comment (depombo) [reply dashboard/src/pages/api/run.ts:112]: oh my bad, got it

**Review by depombo — APPROVED** [review]

File: dashboard/src/pages/api/run.ts [hunk 3]
```diff
@@ -114,10 +120,12 @@ async function runSql(sql: string, dbAlias: string, username: string, password:
         app: 'run',
         env: process.env.IASQL_ENV,
         meta: {
+          sql,
           error: e.message,
           stack: e.stack,
         },
       });
+      res.status(500).json({ error: `Connection interruption while executing query ${sql}` });
```
Comment (dfellis) [inline dashboard/src/pages/api/run.ts:128]: If we're going to hide the actual message it may make sense to generate a UUID and include it in both the `logger.error` and this JSON blob so if we trigger the error while running locally we can check the mezmo logs for that exact UUID and get the details.

**Review by dfellis — APPROVED** [review]
