### PR TITLE
Fix command initialization

### LINKED ISSUE #2131: On start cmd/ctrl+enter is not working
After changing tabs it start working as expected

### PR DESCRIPTION
**Pull request by aguillenv**
Resolves #2131

### CODE REVIEW

File: dashboard/src/components/IasqlEditor.tsx [hunk 1]
```diff
@@ -97,19 +97,20 @@ export default function IasqlEditor() {
...
-      exec: () => handleQueryToRunUpdate(selectedDb, editorSelectedTab),
-    };
     if (editorTabs?.[editorSelectedTab]?.isRunning) {
       editorRef?.current?.editor?.commands?.removeCommand(command);
     } else {
       editorRef?.current?.editor?.commands?.removeCommand(command);
       editorRef?.current?.editor?.commands?.addCommand(command);
     }
-  }, [handleQueryToRunUpdate, selectedDb, editorTabs, editorSelectedTab]);
+  }, [editorTabs, editorSelectedTab, editorRef.current]);
```
Comment (mtp1376) [inline dashboard/src/components/IasqlEditor.tsx:113]: Just for my own learning: why are you passing `editorRef.current` here?

**Review by mtp1376 — APPROVED** [review]

File: dashboard/src/components/IasqlEditor.tsx (hunk 1 above)
Comment (aguillenv) [reply dashboard/src/components/IasqlEditor.tsx:113]: Every variable that we pass in the `dependecyList` will trigger the hook on any change

**Review by yrobla — APPROVED** [review]

**Review by dfellis — APPROVED** [review]

**Review by depombo — APPROVED** [review]
